<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DeploySeeder extends Seeder
{
    public function run(): void
    {
        function translit($value)
        {
            $converter = array(
                'а' => 'a',
                'б' => 'b',
                'в' => 'v',
                'г' => 'g',
                'д' => 'd',
                'е' => 'e',
                'ё' => 'e',
                'ж' => 'zh',
                'з' => 'z',
                'и' => 'i',
                'й' => 'y',
                'к' => 'k',
                'л' => 'l',
                'м' => 'm',
                'н' => 'n',
                'о' => 'o',
                'п' => 'p',
                'р' => 'r',
                'с' => 's',
                'т' => 't',
                'у' => 'u',
                'ф' => 'f',
                'х' => 'h',
                'ц' => 'c',
                'ч' => 'ch',
                'ш' => 'sh',
                'щ' => 'sch',
                'ь' => '',
                'ы' => 'y',
                'ъ' => '',
                'э' => 'e',
                'ю' => 'yu',
                'я' => 'ya',

                'А' => 'A',
                'Б' => 'B',
                'В' => 'V',
                'Г' => 'G',
                'Д' => 'D',
                'Е' => 'E',
                'Ё' => 'E',
                'Ж' => 'Zh',
                'З' => 'Z',
                'И' => 'I',
                'Й' => 'Y',
                'К' => 'K',
                'Л' => 'L',
                'М' => 'M',
                'Н' => 'N',
                'О' => 'O',
                'П' => 'P',
                'Р' => 'R',
                'С' => 'S',
                'Т' => 'T',
                'У' => 'U',
                'Ф' => 'F',
                'Х' => 'H',
                'Ц' => 'C',
                'Ч' => 'Ch',
                'Ш' => 'Sh',
                'Щ' => 'Sch',
                'Ь' => '',
                'Ы' => 'Y',
                'Ъ' => '',
                'Э' => 'E',
                'Ю' => 'Yu',
                'Я' => 'Ya',
            );

            $value = strtr($value, $converter);
            return $value;
        }

        /* Add regions*/
        $regionsInRussia = array([
            ['code' => 0, 'name' =>  'Россия', 'InEnglish' => 'Russia'],
            ['code' => 1, 'name' =>  'Адыгея', 'InEnglish' => 'Adygeya Republic'],
            ['code' => 4, 'name' =>  'Алтай', 'InEnglish' => ''],
            ['code' => 28, 'name' =>  'Алтайский край', 'InEnglish' => 'Altai Krai'],
            ['code' => 29, 'name' =>  'Амурская область', 'InEnglish' => ''],
            ['code' => 29, 'name' =>  'Архангельская область', 'InEnglish' => ''],
            ['code' => 30, 'name' =>  'Астраханская область', 'InEnglish' => ''],
            ['code' => 2, 'name' =>  'Башкортостан', 'InEnglish' => ''],
            ['code' => 31, 'name' =>  'Белгородская область', 'InEnglish' => ''],
            ['code' => 32, 'name' => 'Брянская область', 'InEnglish' => ''],
            ['code' => 3, 'name' => 'Бурятия', 'InEnglish' => ''],
            ['code' => 33, 'name' => 'Владимирская область', 'InEnglish' => ''],
            ['code' => 34, 'name' => 'Волгоградская область', 'InEnglish' => ''],
            ['code' => 35, 'name' => 'Вологодская область', 'InEnglish' => ''],
            ['code' => 36, 'name' => 'Воронежская область', 'InEnglish' => ''],
            ['code' => 5, 'name' => 'Дагестан', 'InEnglish' => ''],
            ['code' => 79, 'name' => 'Еврейская АО', 'InEnglish' => ''],
            ['code' => 75, 'name' => 'Забайкальский край', 'InEnglish' => ''],
            ['code' => 37, 'name' => 'Ивановская область', 'InEnglish' => ''],
            ['code' => 6, 'name' => 'Ингушетия', 'InEnglish' => ''],
            ['code' => 38, 'name' => 'Иркутская область', 'InEnglish' => ''],
            ['code' => 7, 'name' => 'Кабардино-Балкария', 'InEnglish' => ''],
            ['code' => 39, 'name' => 'Калининградская область', 'InEnglish' => ''],
            ['code' => 8, 'name' => 'Калмыкия', 'InEnglish' => ''],
            ['code' => 40, 'name' => 'Калужская область', 'InEnglish' => ''],
            ['code' => 41, 'name' => 'Камчатский край', 'InEnglish' => ''],
            ['code' => 9, 'name' => 'Карачаево-Черкессия', 'InEnglish' => ''],
            ['code' => 10, 'name' => 'Карелия', 'InEnglish' => ''],
            ['code' => 42, 'name' => 'Кемеровская область', 'InEnglish' => ''],
            ['code' => 43, 'name' => 'Кировская область', 'InEnglish' => ''],
            ['code' => 11, 'name' => 'Коми', 'InEnglish' => ''],
            ['code' => 44, 'name' => 'Костромская область', 'InEnglish' => ''],
            ['code' => 23, 'name' => 'Краснодарский край', 'InEnglish' => ''],
            ['code' => 24, 'name' => 'Красноярский край', 'InEnglish' => ''],
            ['code' => 45, 'name' => 'Курганская область', 'InEnglish' => ''],
            ['code' => 46, 'name' => 'Курская область', 'InEnglish' => ''],
            ['code' => 47, 'name' => 'Ленинградская область', 'InEnglish' => ''],
            ['code' => 48, 'name' => 'Липецкая область', 'InEnglish' => ''],
            ['code' => 49, 'name' => 'Магаданская область', 'InEnglish' => ''],
            ['code' => 12, 'name' => 'Марий Эл', 'InEnglish' => ''],
            ['code' => 13, 'name' => 'Мордовия', 'InEnglish' => ''],
            ['code' => 77, 'name' => 'Москва', 'InEnglish' => ''],
            ['code' => 50, 'name' => 'Московская область', 'InEnglish' => ''],
            ['code' => 51, 'name' => 'Мурманская область', 'InEnglish' => ''],
            ['code' => 83, 'name' => 'Ненецкий АО', 'InEnglish' => ''],
            ['code' => 52, 'name' => 'Нижегородская область', 'InEnglish' => ''],
            ['code' => 53, 'name' => 'Новгородская область', 'InEnglish' => ''],
            ['code' => 54, 'name' => 'Новосибирская область', 'InEnglish' => 'Novosibirsk Oblast'],
            ['code' => 55, 'name' => 'Омская область', 'InEnglish' => ''],
            ['code' => 56, 'name' => 'Оренбургская область', 'InEnglish' => ''],
            ['code' => 57, 'name' => 'Орловская область', 'InEnglish' => ''],
            ['code' => 58, 'name' => 'Пензенская область', 'InEnglish' => ''],
            ['code' => 59, 'name' => 'Пермский край', 'InEnglish' => ''],
            ['code' => 25, 'name' => 'Приморский край', 'InEnglish' => ''],
            ['code' => 60, 'name' => 'Псковская область', 'InEnglish' => ''],
            ['code' => 61, 'name' => 'Ростовская область', 'InEnglish' => ''],
            ['code' => 62, 'name' => 'Рязанская область', 'InEnglish' => ''],
            ['code' => 63, 'name' => 'Самарская область', 'InEnglish' => ''],
            ['code' => 78, 'name' => 'Санкт-Петербург', 'InEnglish' => ''],
            ['code' => 64, 'name' => 'Саратовская область', 'InEnglish' => ''],
            ['code' => 14, 'name' => 'Саха (Якутия)', 'InEnglish' => ''],
            ['code' => 65, 'name' => 'Сахалинская область', 'InEnglish' => ''],
            ['code' => 66, 'name' => 'Свердловская область', 'InEnglish' => ''],
            ['code' => 15, 'name' => 'Северная Осетия - Алания', 'InEnglish' => ''],
            ['code' => 67, 'name' => 'Смоленская область', 'InEnglish' => ''],
            ['code' => 26, 'name' => 'Ставропольский край', 'InEnglish' => ''],
            ['code' => 68, 'name' => 'Тамбовская область', 'InEnglish' => ''],
            ['code' => 16, 'name' => 'Татарстан', 'InEnglish' => ''],
            ['code' => 69, 'name' => 'Тверская область', 'InEnglish' => ''],
            ['code' => 70, 'name' => 'Томская область', 'InEnglish' => ''],
            ['code' => 71, 'name' => 'Тульская область', 'InEnglish' => ''],
            ['code' => 17, 'name' => 'Тыва', 'InEnglish' => ''],
            ['code' => 72, 'name' => 'Тюменская область', 'InEnglish' => ''],
            ['code' => 18, 'name' => 'Удмуртия', 'InEnglish' => ''],
            ['code' => 73, 'name' => 'Ульяновская область', 'InEnglish' => ''],
            ['code' => 27, 'name' => 'Хабаровский край', 'InEnglish' => ''],
            ['code' => 19, 'name' => 'Хакасия', 'InEnglish' => ''],
            ['code' => 86, 'name' => 'Ханты-Мансийский АО - Югра', 'InEnglish' => ''],
            ['code' => 74, 'name' => 'Челябинская область', 'InEnglish' => ''],
            ['code' => 20, 'name' => 'Чеченская республика', 'InEnglish' => ''],
            ['code' => 21, 'name' => 'Чувашская республика', 'InEnglish' => ''],
            ['code' => 87, 'name' => 'Чукотский АО', 'InEnglish' => ''],
            ['code' => 89, 'name' => 'Ямало-Ненецкий АО', 'InEnglish' => ''],
            ['code' => 76, 'name' => 'Ярославская область', 'InEnglish' => ''],
            ['code' => 82, 'name' => 'Крым', 'InEnglish' => ''],
            ['code' => 92, 'name' => 'Севастополь', 'InEnglish' => '']
        ]);

        foreach ($regionsInRussia as $regionInRussia) {
            foreach ($regionInRussia as $region) {
                if ($region['name'] == 'Россия') {
                    DB::table('regions')->insert(['name' => $region['name'], 'InEnglish' => 'Russia', 'code' => $region['code']]);
                } elseif ($region['name'] == 'Ставропольский край') {
                    DB::table('regions')->insert(['name' => $region['name'], 'InEnglish' => 'Stavropol Kray', 'code' => $region['code']]);
                } else {
                    DB::table('regions')->insert(['name' => $region['name'], 'InEnglish' => translit($region['name']), 'code' => $region['code']]);
                }
            }
        }

        /* Add cities*/
        $citiesInRussia = array([
            ['region_id' => 1, 'name' => 'не выбрано'],
            ['region_id' => 2, 'name' => 'Майкоп'],
            ['region_id' => 3, 'name' => 'Горно-Алтайск'],
            ['region_id' => 4, 'name' => 'Барнаул'],
            ['region_id' => 4, 'name' => 'Бийск'],
            ['region_id' => 4, 'name' => 'Рубцовск'],
            ['region_id' => 4, 'name' => 'Новоалтайск'],
            ['region_id' => 4, 'name' => 'Заринск'],
            ['region_id' => 5, 'name' => 'Благовещенск (Амурская область)'],
            ['region_id' => 5, 'name' => 'Белогорск (Амурская область)'],
            ['region_id' => 5, 'name' => 'Свободный'],
            ['region_id' => 6, 'name' => 'Архангельск'],
            ['region_id' => 6, 'name' => 'Северодвинск'],
            ['region_id' => 6, 'name' => 'Котлас'],
            ['region_id' => 7, 'name' => 'Астрахань'],
            ['region_id' => 7, 'name' => 'Ахтубинск'],
            ['region_id' => 7, 'name' => 'Знаменск'],
            ['region_id' => 8, 'name' => 'Уфа'],
            ['region_id' => 8, 'name' => 'Стерлитамак'],
            ['region_id' => 8, 'name' => 'Салават'],
            ['region_id' => 8, 'name' => 'Нефтекамск'],
            ['region_id' => 8, 'name' => 'Октябрьский'],
            ['region_id' => 8, 'name' => 'Белорецк'],
            ['region_id' => 8, 'name' => 'Благовещенск (Башкортостан)'],
            ['region_id' => 9, 'name' => 'Белгород'],
            ['region_id' => 9, 'name' => 'Старый Оскол'],
            ['region_id' => 9, 'name' => 'Губкин'],
            ['region_id' => 9, 'name' => 'Шебекино'],
            ['region_id' => 9, 'name' => 'Новый Оскол'],
            ['region_id' => 10, 'name' => 'Брянск'],
            ['region_id' => 10, 'name' => 'Клинцы'],
            ['region_id' => 11, 'name' => 'Улан-Удэ'],
            ['region_id' => 11, 'name' => 'Северобайкальск'],
            ['region_id' => 12, 'name' => 'Владимир'],
            ['region_id' => 12, 'name' => 'Ковров'],
            ['region_id' => 12, 'name' => 'Муром'],
            ['region_id' => 12, 'name' => 'Александров'],
            ['region_id' => 12, 'name' => 'Гусь-Хрустальный'],
            ['region_id' => 12, 'name' => 'Киржач'],
            ['region_id' => 13, 'name' => 'Волгоград'],
            ['region_id' => 13, 'name' => 'Волжский'],
            ['region_id' => 13, 'name' => 'Камышин'],
            ['region_id' => 13, 'name' => 'Калач-на-Дону'],
            ['region_id' => 14, 'name' => 'Череповец'],
            ['region_id' => 14, 'name' => 'Вологда'],
            ['region_id' => 14, 'name' => 'Сокол'],
            ['region_id' => 15, 'name' => 'Воронеж'],
            ['region_id' => 15, 'name' => 'Борисоглебск'],
            ['region_id' => 15, 'name' => 'Россошь'],
            ['region_id' => 15, 'name' => 'Лиски'],
            ['region_id' => 15, 'name' => 'Павловск'],
            ['region_id' => 16, 'name' => 'Махачкала'],
            ['region_id' => 16, 'name' => 'Хасавюрт'],
            ['region_id' => 16, 'name' => 'Дербент'],
            ['region_id' => 17, 'name' => 'Биробиджан'],
            ['region_id' => 18, 'name' => 'Чита'],
            ['region_id' => 18, 'name' => 'Краснокаменск'],
            ['region_id' => 19, 'name' => 'Иваново'],
            ['region_id' => 19, 'name' => 'Кинешма'],
            ['region_id' => 19, 'name' => 'Шуя'],
            ['region_id' => 20, 'name' => 'Назрань'],
            ['region_id' => 21, 'name' => 'Иркутск'],
            ['region_id' => 21, 'name' => 'Братск'],
            ['region_id' => 21, 'name' => 'Ангарск'],
            ['region_id' => 21, 'name' => 'Усть-Илимск'],
            ['region_id' => 22, 'name' => 'Нальчик'],
            ['region_id' => 22, 'name' => 'Прохладный'],
            ['region_id' => 23, 'name' => 'Калининград'],
            ['region_id' => 23, 'name' => 'Советск (Калининградская область)'],
            ['region_id' => 24, 'name' => 'Элиста'],
            ['region_id' => 25, 'name' => 'Калуга'],
            ['region_id' => 25, 'name' => 'Обнинск'],
            ['region_id' => 26, 'name' => 'Петропавловск-Камчатский'],
            ['region_id' => 26, 'name' => 'Елизово'],
            ['region_id' => 26, 'name' => 'Вилючинск'],
            ['region_id' => 27, 'name' => 'Черкесск'],
            ['region_id' => 28, 'name' => 'Петрозаводск'],
            ['region_id' => 28, 'name' => 'Кондопога'],
            ['region_id' => 29, 'name' => 'Новокузнецк'],
            ['region_id' => 29, 'name' => 'Кемерово'],
            ['region_id' => 29, 'name' => 'Прокопьевск'],
            ['region_id' => 29, 'name' => 'Ленинск-Кузнецкий'],
            ['region_id' => 29, 'name' => 'Междуреченск'],
            ['region_id' => 29, 'name' => 'Киселёвск'],
            ['region_id' => 29, 'name' => 'Юрга'],
            ['region_id' => 30, 'name' => 'Киров (Кировская область)'],
            ['region_id' => 30, 'name' => 'Кирово-Чепецк'],
            ['region_id' => 31, 'name' => 'Сыктывкар'],
            ['region_id' => 31, 'name' => 'Ухта'],
            ['region_id' => 31, 'name' => 'Воркута'],
            ['region_id' => 31, 'name' => 'Печора'],
            ['region_id' => 32, 'name' => 'Кострома'],
            ['region_id' => 33, 'name' => 'Краснодар'],
            ['region_id' => 33, 'name' => 'Сочи'],
            ['region_id' => 33, 'name' => 'Новороссийск'],
            ['region_id' => 33, 'name' => 'Армавир'],
            ['region_id' => 33, 'name' => 'Ейск'],
            ['region_id' => 33, 'name' => 'Кропоткин'],
            ['region_id' => 33, 'name' => 'Туапсе'],
            ['region_id' => 33, 'name' => 'Тихорецк'],
            ['region_id' => 33, 'name' => 'Анапа'],
            ['region_id' => 33, 'name' => 'Белореченск'],
            ['region_id' => 33, 'name' => 'Геленджик'],
            ['region_id' => 34, 'name' => 'Красноярск'],
            ['region_id' => 34, 'name' => 'Норильск'],
            ['region_id' => 34, 'name' => 'Ачинск'],
            ['region_id' => 34, 'name' => 'Канск'],
            ['region_id' => 34, 'name' => 'Железногорск (Красноярский край)'],
            ['region_id' => 34, 'name' => 'Зеленогорск'],
            ['region_id' => 35, 'name' => 'Курган'],
            ['region_id' => 35, 'name' => 'Шадринск'],
            ['region_id' => 36, 'name' => 'Курск'],
            ['region_id' => 36, 'name' => 'Железногорск (Курская область)'],
            ['region_id' => 36, 'name' => 'Курчатов'],
            ['region_id' => 37, 'name' => 'Гатчина'],
            ['region_id' => 37, 'name' => 'Выборг'],
            ['region_id' => 37, 'name' => 'Сосновый Бор'],
            ['region_id' => 37, 'name' => 'Тихвин'],
            ['region_id' => 37, 'name' => 'Кириши'],
            ['region_id' => 37, 'name' => 'Кингисепп'],
            ['region_id' => 37, 'name' => 'Всеволожск'],
            ['region_id' => 37, 'name' => 'Волхов'],
            ['region_id' => 37, 'name' => 'Сертолово'],
            ['region_id' => 37, 'name' => 'Луга'],
            ['region_id' => 37, 'name' => 'Тосно'],
            ['region_id' => 37, 'name' => 'Сланцы'],
            ['region_id' => 37, 'name' => 'Кировск (Ленинградская область)'],
            ['region_id' => 37, 'name' => 'Лодейное Поле'],
            ['region_id' => 37, 'name' => 'Пикалёво'],
            ['region_id' => 37, 'name' => 'Отрадное'],
            ['region_id' => 37, 'name' => 'Подпорожье'],
            ['region_id' => 37, 'name' => 'Коммунар'],
            ['region_id' => 37, 'name' => 'Приозерск'],
            ['region_id' => 37, 'name' => 'Никольское'],
            ['region_id' => 37, 'name' => 'Бокситогорск'],
            ['region_id' => 37, 'name' => 'Светогорск'],
            ['region_id' => 37, 'name' => 'Сясьстрой'],
            ['region_id' => 37, 'name' => 'Шлиссельбург'],
            ['region_id' => 37, 'name' => 'Сиверский'],
            ['region_id' => 37, 'name' => 'Волосово'],
            ['region_id' => 37, 'name' => 'Ивангород'],
            ['region_id' => 37, 'name' => 'Вырица'],
            ['region_id' => 37, 'name' => 'Поселок им. Морозова'],
            ['region_id' => 38, 'name' => 'Липецк'],
            ['region_id' => 38, 'name' => 'Елец'],
            ['region_id' => 39, 'name' => 'Магадан'],
            ['region_id' => 40, 'name' => 'Йошкар-Ола'],
            ['region_id' => 40, 'name' => 'Волжск'],
            ['region_id' => 41, 'name' => 'Саранск'],
            ['region_id' => 41, 'name' => 'Рузаевка'],
            ['region_id' => 43, 'name' => 'Балашиха'],
            ['region_id' => 43, 'name' => 'Химки'],
            ['region_id' => 43, 'name' => 'Подольск'],
            ['region_id' => 43, 'name' => 'Королёв'],
            ['region_id' => 43, 'name' => 'Мытищи'],
            ['region_id' => 43, 'name' => 'Люберцы'],
            ['region_id' => 43, 'name' => 'Коломна'],
            ['region_id' => 43, 'name' => 'Электросталь'],
            ['region_id' => 43, 'name' => 'Одинцово'],
            ['region_id' => 43, 'name' => 'Железнодорожный (Балашиха)'],
            ['region_id' => 43, 'name' => 'Серпухов'],
            ['region_id' => 43, 'name' => 'Орехово-Зуево'],
            ['region_id' => 43, 'name' => 'Ногинск'],
            ['region_id' => 43, 'name' => 'Щёлково'],
            ['region_id' => 43, 'name' => 'Сергиев Посад'],
            ['region_id' => 43, 'name' => 'Жуковский'],
            ['region_id' => 43, 'name' => 'Красногорск'],
            ['region_id' => 43, 'name' => 'Пушкино'],
            ['region_id' => 43, 'name' => 'Воскресенск'],
            ['region_id' => 43, 'name' => 'Домодедово'],
            ['region_id' => 43, 'name' => 'Раменское'],
            ['region_id' => 43, 'name' => 'Реутов'],
            ['region_id' => 43, 'name' => 'Долгопрудный'],
            ['region_id' => 43, 'name' => 'Клин'],
            ['region_id' => 43, 'name' => 'Чехов'],
            ['region_id' => 43, 'name' => 'Наро-Фоминск'],
            ['region_id' => 43, 'name' => 'Лобня'],
            ['region_id' => 43, 'name' => 'Егорьевск'],
            ['region_id' => 43, 'name' => 'Ступино'],
            ['region_id' => 43, 'name' => 'Дмитров'],
            ['region_id' => 43, 'name' => 'Дубна'],
            ['region_id' => 43, 'name' => 'Павловский Посад'],
            ['region_id' => 43, 'name' => 'Солнечногорск'],
            ['region_id' => 43, 'name' => 'Ивантеевка'],
            ['region_id' => 42, 'name' => 'Климовск (Москва)'],
            ['region_id' => 43, 'name' => 'Видное'],
            ['region_id' => 43, 'name' => 'Фрязино'],
            ['region_id' => 43, 'name' => 'Лыткарино'],
            ['region_id' => 43, 'name' => 'Дзержинский'],
            ['region_id' => 43, 'name' => 'Кашира'],
            ['region_id' => 43, 'name' => 'Протвино'],
            ['region_id' => 42, 'name' => 'Троицк (Москва)'],
            ['region_id' => 42, 'name' => 'Юбилейный (Москва)'],
            ['region_id' => 43, 'name' => 'Истра'],
            ['region_id' => 43, 'name' => 'Нахабино'],
            ['region_id' => 43, 'name' => 'Краснознаменск (Московская область)'],
            ['region_id' => 43, 'name' => 'Луховицы'],
            ['region_id' => 42, 'name' => 'Щербинка (Москва)'],
            ['region_id' => 43, 'name' => 'Шатура'],
            ['region_id' => 43, 'name' => 'Ликино-Дулёво'],
            ['region_id' => 43, 'name' => 'Можайск'],
            ['region_id' => 43, 'name' => 'Томилино'],
            ['region_id' => 43, 'name' => 'Дедовск'],
            ['region_id' => 43, 'name' => 'Красноармейск (Московская область)'],
            ['region_id' => 43, 'name' => 'Кубинка'],
            ['region_id' => 43, 'name' => 'Озёры'],
            ['region_id' => 43, 'name' => 'Зарайск'],
            ['region_id' => 43, 'name' => 'Калининец'],
            ['region_id' => 43, 'name' => 'Волоколамск'],
            ['region_id' => 43, 'name' => 'Лосино-Петровский'],
            ['region_id' => 43, 'name' => 'Старая Купавна'],
            ['region_id' => 43, 'name' => 'Рошаль'],
            ['region_id' => 43, 'name' => 'Электрогорск'],
            ['region_id' => 43, 'name' => 'Электроугли'],
            ['region_id' => 43, 'name' => 'Черноголовка'],
            ['region_id' => 43, 'name' => 'Котельники'],
            ['region_id' => 43, 'name' => 'Пущино'],
            ['region_id' => 43, 'name' => 'Красково'],
            ['region_id' => 44, 'name' => 'Мурманск'],
            ['region_id' => 44, 'name' => 'Апатиты'],
            ['region_id' => 44, 'name' => 'Североморск'],
            ['region_id' => 45, 'name' => 'Нарьян-Мар'],
            ['region_id' => 46, 'name' => 'Нижний Новгород'],
            ['region_id' => 46, 'name' => 'Дзержинск'],
            ['region_id' => 46, 'name' => 'Арзамас'],
            ['region_id' => 46, 'name' => 'Саров'],
            ['region_id' => 46, 'name' => 'Бор'],
            ['region_id' => 46, 'name' => 'Кстово'],
            ['region_id' => 46, 'name' => 'Павлово'],
            ['region_id' => 46, 'name' => 'Выкса'],
            ['region_id' => 46, 'name' => 'Балахна'],
            ['region_id' => 47, 'name' => 'Великий Новгород'],
            ['region_id' => 47, 'name' => 'Боровичи'],
            ['region_id' => 47, 'name' => 'Старая Русса'],
            ['region_id' => 48, 'name' => 'Новосибирск'],
            ['region_id' => 48, 'name' => 'Бердск'],
            ['region_id' => 48, 'name' => 'Куйбышев'],
            ['region_id' => 49, 'name' => 'Омск'],
            ['region_id' => 50, 'name' => 'Оренбург'],
            ['region_id' => 50, 'name' => 'Орск'],
            ['region_id' => 50, 'name' => 'Новотроицк'],
            ['region_id' => 50, 'name' => 'Бузулук'],
            ['region_id' => 51, 'name' => 'Орёл'],
            ['region_id' => 51, 'name' => 'Ливны'],
            ['region_id' => 51, 'name' => 'Мценск'],
            ['region_id' => 52, 'name' => 'Пенза'],
            ['region_id' => 52, 'name' => 'Кузнецк'],
            ['region_id' => 52, 'name' => 'Заречный (Пензенская область)'],
            ['region_id' => 52, 'name' => 'Каменка'],
            ['region_id' => 53, 'name' => 'Пермь'],
            ['region_id' => 53, 'name' => 'Березники'],
            ['region_id' => 53, 'name' => 'Соликамск'],
            ['region_id' => 53, 'name' => 'Чайковский'],
            ['region_id' => 53, 'name' => 'Лысьва'],
            ['region_id' => 53, 'name' => 'Кунгур'],
            ['region_id' => 53, 'name' => 'Краснокамск'],
            ['region_id' => 54, 'name' => 'Владивосток'],
            ['region_id' => 54, 'name' => 'Находка'],
            ['region_id' => 54, 'name' => 'Уссурийск'],
            ['region_id' => 54, 'name' => 'Артём'],
            ['region_id' => 55, 'name' => 'Псков'],
            ['region_id' => 55, 'name' => 'Великие Луки'],
            ['region_id' => 56, 'name' => 'Ростов-на-Дону'],
            ['region_id' => 56, 'name' => 'Таганрог'],
            ['region_id' => 56, 'name' => 'Шахты'],
            ['region_id' => 56, 'name' => 'Новочеркасск'],
            ['region_id' => 56, 'name' => 'Волгодонск'],
            ['region_id' => 56, 'name' => 'Новошахтинск'],
            ['region_id' => 56, 'name' => 'Батайск'],
            ['region_id' => 56, 'name' => 'Каменск-Шахтинский'],
            ['region_id' => 56, 'name' => 'Азов'],
            ['region_id' => 56, 'name' => 'Гуково'],
            ['region_id' => 56, 'name' => 'Сальск'],
            ['region_id' => 56, 'name' => 'Донецк'],
            ['region_id' => 56, 'name' => 'Белая Калитва'],
            ['region_id' => 57, 'name' => 'Рязань'],
            ['region_id' => 57, 'name' => 'Касимов'],
            ['region_id' => 58, 'name' => 'Самара'],
            ['region_id' => 58, 'name' => 'Тольятти'],
            ['region_id' => 58, 'name' => 'Сызрань'],
            ['region_id' => 58, 'name' => 'Новокуйбышевск'],
            ['region_id' => 58, 'name' => 'Чапаевск'],
            ['region_id' => 58, 'name' => 'Жигулёвск'],
            ['region_id' => 60, 'name' => 'Саратов'],
            ['region_id' => 60, 'name' => 'Энгельс'],
            ['region_id' => 60, 'name' => 'Балаково'],
            ['region_id' => 60, 'name' => 'Балашов'],
            ['region_id' => 60, 'name' => 'Вольск'],
            ['region_id' => 61, 'name' => 'Якутск'],
            ['region_id' => 61, 'name' => 'Нерюнгри'],
            ['region_id' => 61, 'name' => 'Мирный'],
            ['region_id' => 62, 'name' => 'Южно-Сахалинск'],
            ['region_id' => 63, 'name' => 'Екатеринбург'],
            ['region_id' => 63, 'name' => 'Нижний Тагил'],
            ['region_id' => 63, 'name' => 'Каменск-Уральский'],
            ['region_id' => 63, 'name' => 'Первоуральск'],
            ['region_id' => 63, 'name' => 'Серов'],
            ['region_id' => 63, 'name' => 'Новоуральск'],
            ['region_id' => 63, 'name' => 'Асбест'],
            ['region_id' => 63, 'name' => 'Полевской'],
            ['region_id' => 63, 'name' => 'Ревда'],
            ['region_id' => 63, 'name' => 'Краснотурьинск'],
            ['region_id' => 64, 'name' => 'Владикавказ'],
            ['region_id' => 64, 'name' => 'Моздок'],
            ['region_id' => 65, 'name' => 'Смоленск'],
            ['region_id' => 65, 'name' => 'Вязьма'],
            ['region_id' => 66, 'name' => 'Ставрополь'],
            ['region_id' => 66, 'name' => 'Пятигорск'],
            ['region_id' => 66, 'name' => 'Кисловодск'],
            ['region_id' => 66, 'name' => 'Ессентуки'],
            ['region_id' => 66, 'name' => 'Минеральные Воды'],
            ['region_id' => 66, 'name' => 'Будённовск'],
            ['region_id' => 67, 'name' => 'Тамбов'],
            ['region_id' => 67, 'name' => 'Мичуринск'],
            ['region_id' => 68, 'name' => 'Казань'],
            ['region_id' => 68, 'name' => 'Набережные Челны'],
            ['region_id' => 68, 'name' => 'Нижнекамск'],
            ['region_id' => 68, 'name' => 'Альметьевск'],
            ['region_id' => 68, 'name' => 'Зеленодольск'],
            ['region_id' => 68, 'name' => 'Бугульма'],
            ['region_id' => 69, 'name' => 'Тверь'],
            ['region_id' => 69, 'name' => 'Ржев'],
            ['region_id' => 70, 'name' => 'Томск'],
            ['region_id' => 70, 'name' => 'Северск'],
            ['region_id' => 71, 'name' => 'Тула'],
            ['region_id' => 71, 'name' => 'Новомосковск'],
            ['region_id' => 71, 'name' => 'Узловая'],
            ['region_id' => 72, 'name' => 'Кызыл'],
            ['region_id' => 73, 'name' => 'Тюмень'],
            ['region_id' => 73, 'name' => 'Тобольск'],
            ['region_id' => 74, 'name' => 'Ижевск'],
            ['region_id' => 74, 'name' => 'Сарапул'],
            ['region_id' => 74, 'name' => 'Глазов'],
            ['region_id' => 74, 'name' => 'Воткинск'],
            ['region_id' => 75, 'name' => 'Ульяновск'],
            ['region_id' => 75, 'name' => 'Димитровград'],
            ['region_id' => 76, 'name' => 'Хабаровск'],
            ['region_id' => 76, 'name' => 'Комсомольск-на-Амуре'],
            ['region_id' => 76, 'name' => 'Амурск'],
            ['region_id' => 77, 'name' => 'Абакан'],
            ['region_id' => 77, 'name' => 'Черногорск'],
            ['region_id' => 78, 'name' => 'Сургут'],
            ['region_id' => 78, 'name' => 'Нижневартовск'],
            ['region_id' => 78, 'name' => 'Нефтеюганск'],
            ['region_id' => 78, 'name' => 'Ханты-Мансийск'],
            ['region_id' => 79, 'name' => 'Челябинск'],
            ['region_id' => 79, 'name' => 'Магнитогорск'],
            ['region_id' => 79, 'name' => 'Златоуст'],
            ['region_id' => 79, 'name' => 'Миасс'],
            ['region_id' => 79, 'name' => 'Копейск'],
            ['region_id' => 79, 'name' => 'Озёрск'],
            ['region_id' => 79, 'name' => 'Троицк'],
            ['region_id' => 79, 'name' => 'Снежинск'],
            ['region_id' => 79, 'name' => 'Сатка'],
            ['region_id' => 80, 'name' => 'Грозный'],
            ['region_id' => 80, 'name' => 'Урус-Мартан'],
            ['region_id' => 81, 'name' => 'Чебоксары'],
            ['region_id' => 81, 'name' => 'Новочебоксарск'],
            ['region_id' => 83, 'name' => 'Новый Уренгой'],
            ['region_id' => 83, 'name' => 'Ноябрьск'],
            ['region_id' => 84, 'name' => 'Ярославль'],
            ['region_id' => 84, 'name' => 'Рыбинск'],
            ['region_id' => 84, 'name' => 'Переславль-Залесский'],
            ['region_id' => 42, 'name' => 'Москва'],
            ['region_id' => 59, 'name' => 'Санкт-Петербург'],
            ['region_id' => 77, 'name' => 'Абаза'],
            ['region_id' => 50, 'name' => 'Абдулино'],
            ['region_id' => 33, 'name' => 'Абинск'],
            ['region_id' => 8,  'name' => 'Агидель'],
            ['region_id' => 68, 'name' => 'Агрыз'],
            ['region_id' => 2,  'name' => 'Адыгейск'],
            ['region_id' => 68, 'name' => 'Азнакаево'],
            ['region_id' => 72, 'name' => 'Ак-Довурак'],
            ['region_id' => 56, 'name' => 'Аксай'],
            ['region_id' => 64, 'name' => 'Алагир'],
            ['region_id' => 63, 'name' => 'Алапаевск'],
            ['region_id' => 81, 'name' => 'Алатырь'],
            ['region_id' => 61, 'name' => 'Алдан'],
            ['region_id' => 4,  'name' => 'Алейск'],
            ['region_id' => 53, 'name' => 'Александровск'],
            ['region_id' => 62, 'name' => 'Александровск-Сахалинский'],
            ['region_id' => 9,  'name' => 'Алексеевка'],
            ['region_id' => 71, 'name' => 'Алексин'],
            ['region_id' => 21, 'name' => 'Алзамай'],
            ['region_id' => 82, 'name' => 'Анадырь'],
            ['region_id' => 69, 'name' => 'Андреаполь'],
            ['region_id' => 29, 'name' => 'Анжеро-Судженск'],
            ['region_id' => 62, 'name' => 'Анива'],
            ['region_id' => 43, 'name' => 'Апрелевка'],
            ['region_id' => 33, 'name' => 'Апшеронск'],
            ['region_id' => 63, 'name' => 'Арамиль'],
            ['region_id' => 80, 'name' => 'Аргун'],
            ['region_id' => 41, 'name' => 'Ардатов'],
            ['region_id' => 64, 'name' => 'Ардон'],
            ['region_id' => 60, 'name' => 'Аркадак'],
            ['region_id' => 54, 'name' => 'Арсеньев'],
            ['region_id' => 68, 'name' => 'Арск'],
            ['region_id' => 34, 'name' => 'Артёмовск'],
            ['region_id' => 63, 'name' => 'Артёмовский'],
            ['region_id' => 70, 'name' => 'Асино'],
            ['region_id' => 60, 'name' => 'Аткарск'],
            ['region_id' => 79, 'name' => 'Аша'],
            ['region_id' => 14, 'name' => 'Бабаево'],
            ['region_id' => 11, 'name' => 'Бабушкин'],
            ['region_id' => 68, 'name' => 'Бавлы'],
            ['region_id' => 23, 'name' => 'Багратионовск'],
            ['region_id' => 21, 'name' => 'Байкальск'],
            ['region_id' => 8,  'name' => 'Баймак'],
            ['region_id' => 79, 'name' => 'Бакал'],
            ['region_id' => 22, 'name' => 'Баксан'],
            ['region_id' => 25, 'name' => 'Балабаново'],
            ['region_id' => 18, 'name' => 'Балей'],
            ['region_id' => 23, 'name' => 'Балтийск'],
            ['region_id' => 48, 'name' => 'Барабинск'],
            ['region_id' => 75, 'name' => 'Барыш'],
            ['region_id' => 69, 'name' => 'Бежецк'],
            ['region_id' => 71, 'name' => 'Белёв'],
            ['region_id' => 30, 'name' => 'Белая Холуница'],
            ['region_id' => 8,  'name' => 'Белебей'],
            ['region_id' => 52, 'name' => 'Белинский'],
            ['region_id' => 29, 'name' => 'Белово'],
            ['region_id' => 14, 'name' => 'Белозерск'],
            ['region_id' => 4,  'name' => 'Белокуриха'],
            ['region_id' => 28, 'name' => 'Беломорск'],
            ['region_id' => 25, 'name' => 'Белоусово'],
            ['region_id' => 78, 'name' => 'Белоярский'],
            ['region_id' => 69, 'name' => 'Белый'],
            ['region_id' => 29, 'name' => 'Березовский (Кемеровская область)'],
            ['region_id' => 63, 'name' => 'Березовский (Свердловская область)'],
            ['region_id' => 64, 'name' => 'Беслан'],
            ['region_id' => 76, 'name' => 'Бикин'],
            ['region_id' => 82, 'name' => 'Билибино'],
            ['region_id' => 8,  'name' => 'Бирск'],
            ['region_id' => 21, 'name' => 'Бирюсинск'],
            ['region_id' => 9,  'name' => 'Бирюч'],
            ['region_id' => 66, 'name' => 'Благодарный'],
            ['region_id' => 15, 'name' => 'Бобров'],
            ['region_id' => 63, 'name' => 'Богданович'],
            ['region_id' => 71, 'name' => 'Богородицк'],
            ['region_id' => 46, 'name' => 'Богородск'],
            ['region_id' => 34, 'name' => 'Боготол'],
            ['region_id' => 15, 'name' => 'Богучар'],
            ['region_id' => 21, 'name' => 'Бодайбо'],
            ['region_id' => 68, 'name' => 'Болгар'],
            ['region_id' => 69, 'name' => 'Бологое'],
            ['region_id' => 48, 'name' => 'Болотное'],
            ['region_id' => 71, 'name' => 'Болохово'],
            ['region_id' => 51, 'name' => 'Болхов'],
            ['region_id' => 54, 'name' => 'Большой Камень'],
            ['region_id' => 18, 'name' => 'Борзя'],
            ['region_id' => 25, 'name' => 'Боровск'],
            ['region_id' => 34, 'name' => 'Бородино'],
            ['region_id' => 43, 'name' => 'Бронницы'],
            ['region_id' => 50, 'name' => 'Бугуруслан'],
            ['region_id' => 68, 'name' => 'Буинск'],
            ['region_id' => 32, 'name' => 'Буй'],
            ['region_id' => 16, 'name' => 'Буйнакск'],
            ['region_id' => 15, 'name' => 'Бутурлиновка'],
            ['region_id' => 47, 'name' => 'Валдай'],
            ['region_id' => 9,  'name' => 'Валуйки'],
            ['region_id' => 65, 'name' => 'Велиж'],
            ['region_id' => 14, 'name' => 'Великий Устюг'],
            ['region_id' => 6,  'name' => 'Вельск'],
            ['region_id' => 71, 'name' => 'Венёв'],
            ['region_id' => 53, 'name' => 'Верещагино'],
            ['region_id' => 43, 'name' => 'Верея'],
            ['region_id' => 79, 'name' => 'Верхнеуральск'],
            ['region_id' => 63, 'name' => 'Верхний Тагил'],
            ['region_id' => 79, 'name' => 'Верхний Уфалей'],
            ['region_id' => 63, 'name' => 'Верхняя Пышма'],
            ['region_id' => 63, 'name' => 'Верхняя Салда'],
            ['region_id' => 63, 'name' => 'Верхняя Тура'],
            ['region_id' => 63, 'name' => 'Верхотурье'],
            ['region_id' => 61, 'name' => 'Верхоянск'],
            ['region_id' => 69, 'name' => 'Весьегонск'],
            ['region_id' => 46, 'name' => 'Ветлуга'],
            ['region_id' => 61, 'name' => 'Вилюйск'],
            ['region_id' => 21, 'name' => 'Вихоревка'],
            ['region_id' => 19, 'name' => 'Вичуга'],
            ['region_id' => 32, 'name' => 'Волгореченск'],
            ['region_id' => 46, 'name' => 'Володарск'],
            ['region_id' => 63, 'name' => 'Волчанск'],
            ['region_id' => 46, 'name' => 'Ворсма'],
            ['region_id' => 31, 'name' => 'Вуктыл'],
            ['region_id' => 43, 'name' => 'Высоковск'],
            ['region_id' => 37, 'name' => 'Высоцк'],
            ['region_id' => 14, 'name' => 'Вытегра'],
            ['region_id' => 69, 'name' => 'Вышний Волочёк'],
            ['region_id' => 76, 'name' => 'Вяземский'],
            ['region_id' => 12, 'name' => 'Вязники'],
            ['region_id' => 30, 'name' => 'Вятские Поляны'],
            ['region_id' => 19, 'name' => 'Гаврилов Посад'],
            ['region_id' => 84, 'name' => 'Гаврилов-Ям'],
            ['region_id' => 65, 'name' => 'Гагарин'],
            ['region_id' => 44, 'name' => 'Гаджиево'],
            ['region_id' => 50, 'name' => 'Гай'],
            ['region_id' => 32, 'name' => 'Галич'],
            ['region_id' => 23, 'name' => 'Гвардейск'],
            ['region_id' => 55, 'name' => 'Гдов'],
            ['region_id' => 66, 'name' => 'Георгиевск'],
            ['region_id' => 43, 'name' => 'Голицыно'],
            ['region_id' => 46, 'name' => 'Горбатов'],
            ['region_id' => 53, 'name' => 'Горнозаводск'],
            ['region_id' => 4,  'name' => 'Горняк'],
            ['region_id' => 46, 'name' => 'Городец'],
            ['region_id' => 52, 'name' => 'Городище'],
            ['region_id' => 24, 'name' => 'Городовиковск'],
            ['region_id' => 12, 'name' => 'Гороховец'],
            ['region_id' => 33, 'name' => 'Горячий Ключ'],
            ['region_id' => 9,  'name' => 'Грайворон'],
            ['region_id' => 53, 'name' => 'Гремячинск'],
            ['region_id' => 38, 'name' => 'Грязи'],
            ['region_id' => 14, 'name' => 'Грязовец'],
            ['region_id' => 53, 'name' => 'Губаха'],
            ['region_id' => 83, 'name' => 'Губкинский'],
            ['region_id' => 80, 'name' => 'Гудермес'],
            ['region_id' => 33, 'name' => 'Гулькевичи'],
            ['region_id' => 23, 'name' => 'Гурьевск (Калининградская область)'],
            ['region_id' => 29, 'name' => 'Гурьевск (Кемеровская область)'],
            ['region_id' => 23, 'name' => 'Гусев'],
            ['region_id' => 11, 'name' => 'Гусиноозёрск'],
            ['region_id' => 8,  'name' => 'Давлеканово'],
            ['region_id' => 16, 'name' => 'Дагестанские Огни'],
            ['region_id' => 35, 'name' => 'Далматово'],
            ['region_id' => 54, 'name' => 'Дальнегорск'],
            ['region_id' => 54, 'name' => 'Дальнереченск'],
            ['region_id' => 84, 'name' => 'Данилов'],
            ['region_id' => 38, 'name' => 'Данков'],
            ['region_id' => 63, 'name' => 'Дегтярск'],
            ['region_id' => 65, 'name' => 'Демидов'],
            ['region_id' => 65, 'name' => 'Десногорск'],
            ['region_id' => 34, 'name' => 'Дивногорск'],
            ['region_id' => 64, 'name' => 'Дигора'],
            ['region_id' => 36, 'name' => 'Дмитриев'],
            ['region_id' => 51, 'name' => 'Дмитровск'],
            ['region_id' => 55, 'name' => 'Дно'],
            ['region_id' => 53, 'name' => 'Добрянка'],
            ['region_id' => 62, 'name' => 'Долинск'],
            ['region_id' => 71, 'name' => 'Донской'],
            ['region_id' => 65, 'name' => 'Дорогобуж'],
            ['region_id' => 43, 'name' => 'Дрезна'],
            ['region_id' => 13, 'name' => 'Дубовка'],
            ['region_id' => 34, 'name' => 'Дудинка'],
            ['region_id' => 65, 'name' => 'Духовщина'],
            ['region_id' => 8,  'name' => 'Дюртюли'],
            ['region_id' => 10, 'name' => 'Дятьково'],
            ['region_id' => 68, 'name' => 'Елабуга'],
            ['region_id' => 65, 'name' => 'Ельня'],
            ['region_id' => 79, 'name' => 'Еманжелинск'],
            ['region_id' => 31, 'name' => 'Емва'],
            ['region_id' => 34, 'name' => 'Енисейск'],
            ['region_id' => 25, 'name' => 'Ермолино'],
            ['region_id' => 60, 'name' => 'Ершов'],
            ['region_id' => 71, 'name' => 'Ефремов'],
            ['region_id' => 66, 'name' => 'Железноводск'],
            ['region_id' => 21, 'name' => 'Железногорск-Илимский'],
            ['region_id' => 67, 'name' => 'Жердевка'],
            ['region_id' => 25, 'name' => 'Жиздра'],
            ['region_id' => 13, 'name' => 'Жирновск'],
            ['region_id' => 25, 'name' => 'Жуков'],
            ['region_id' => 10, 'name' => 'Жуковка'],
            ['region_id' => 5,  'name' => 'Завитинск'],
            ['region_id' => 73, 'name' => 'Заводоуковск'],
            ['region_id' => 19, 'name' => 'Заволжск'],
            ['region_id' => 46, 'name' => 'Заволжье'],
            ['region_id' => 38, 'name' => 'Задонск'],
            ['region_id' => 68, 'name' => 'Заинск'],
            ['region_id' => 11, 'name' => 'Закаменск'],
            ['region_id' => 34, 'name' => 'Заозёрный'],
            ['region_id' => 44, 'name' => 'Заозёрск'],
            ['region_id' => 69, 'name' => 'Западная Двина'],
            ['region_id' => 44, 'name' => 'Заполярный'],
            ['region_id' => 63, 'name' => 'Заречный (Свердловская область)'],
            ['region_id' => 40, 'name' => 'Звенигово'],
            ['region_id' => 43, 'name' => 'Звенигород'],
            ['region_id' => 56, 'name' => 'Зверево'],
            ['region_id' => 23, 'name' => 'Зеленоградск'],
            ['region_id' => 66, 'name' => 'Зеленокумск'],
            ['region_id' => 56, 'name' => 'Зерноград'],
            ['region_id' => 5,  'name' => 'Зея'],
            ['region_id' => 21, 'name' => 'Зима'],
            ['region_id' => 10, 'name' => 'Злынка'],
            ['region_id' => 4,  'name' => 'Змеиногорск'],
            ['region_id' => 69, 'name' => 'Зубцов'],
            ['region_id' => 30, 'name' => 'Зуевка'],
            ['region_id' => 63, 'name' => 'Ивдель'],
            ['region_id' => 34, 'name' => 'Игарка'],
            ['region_id' => 16, 'name' => 'Избербаш'],
            ['region_id' => 66, 'name' => 'Изобильный'],
            ['region_id' => 34, 'name' => 'Иланский'],
            ['region_id' => 75, 'name' => 'Инза'],
            ['region_id' => 41, 'name' => 'Инсар'],
            ['region_id' => 31, 'name' => 'Инта'],
            ['region_id' => 66, 'name' => 'Ипатово'],
            ['region_id' => 63, 'name' => 'Ирбит'],
            ['region_id' => 49, 'name' => 'Исилькуль'],
            ['region_id' => 48, 'name' => 'Искитим'],
            ['region_id' => 73, 'name' => 'Ишим'],
            ['region_id' => 8,  'name' => 'Ишимбай'],
            ['region_id' => 14, 'name' => 'Кадников'],
            ['region_id' => 15, 'name' => 'Калач'],
            ['region_id' => 49, 'name' => 'Калачинск'],
            ['region_id' => 60, 'name' => 'Калининск'],
            ['region_id' => 29, 'name' => 'Калтан'],
            ['region_id' => 69, 'name' => 'Калязин'],
            ['region_id' => 74, 'name' => 'Камбарка'],
            ['region_id' => 37, 'name' => 'Каменногорск'],
            ['region_id' => 4,  'name' => 'Камень-на-Оби'],
            ['region_id' => 12, 'name' => 'Камешково'],
            ['region_id' => 7,  'name' => 'Камызяк'],
            ['region_id' => 63, 'name' => 'Камышлов'],
            ['region_id' => 81, 'name' => 'Канаш'],
            ['region_id' => 44, 'name' => 'Кандалакша'],
            ['region_id' => 12, 'name' => 'Карабаново'],
            ['region_id' => 79, 'name' => 'Карабаш'],
            ['region_id' => 20, 'name' => 'Карабулак'],
            ['region_id' => 48, 'name' => 'Карасук'],
            ['region_id' => 27, 'name' => 'Карачаевск'],
            ['region_id' => 10, 'name' => 'Карачев'],
            ['region_id' => 48, 'name' => 'Каргат'],
            ['region_id' => 6,  'name' => 'Каргополь'],
            ['region_id' => 63, 'name' => 'Карпинск'],
            ['region_id' => 79, 'name' => 'Карталы'],
            ['region_id' => 79, 'name' => 'Касли'],
            ['region_id' => 16, 'name' => 'Каспийск'],
            ['region_id' => 79, 'name' => 'Катав-Ивановск'],
            ['region_id' => 35, 'name' => 'Катайск'],
            ['region_id' => 63, 'name' => 'Качканар'],
            ['region_id' => 69, 'name' => 'Кашин'],
            ['region_id' => 70, 'name' => 'Кедровый'],
            ['region_id' => 28, 'name' => 'Кемь'],
            ['region_id' => 53, 'name' => 'Кизел'],
            ['region_id' => 16, 'name' => 'Кизилюрт'],
            ['region_id' => 16, 'name' => 'Кизляр'],
            ['region_id' => 71, 'name' => 'Кимовск'],
            ['region_id' => 69, 'name' => 'Кимры'],
            ['region_id' => 58, 'name' => 'Кинель'],
            ['region_id' => 71, 'name' => 'Киреевск'],
            ['region_id' => 21, 'name' => 'Киренск'],
            ['region_id' => 14, 'name' => 'Кириллов'],
            ['region_id' => 25, 'name' => 'Киров (Калужская область)'],
            ['region_id' => 63, 'name' => 'Кировград'],
            ['region_id' => 44, 'name' => 'Кировск (Мурманская область)'],
            ['region_id' => 30, 'name' => 'Кирс'],
            ['region_id' => 67, 'name' => 'Кирсанов'],
            ['region_id' => 46, 'name' => 'Княгинино'],
            ['region_id' => 44, 'name' => 'Ковдор'],
            ['region_id' => 41, 'name' => 'Ковылкино'],
            ['region_id' => 78, 'name' => 'Когалым'],
            ['region_id' => 34, 'name' => 'Кодинск'],
            ['region_id' => 25, 'name' => 'Козельск'],
            ['region_id' => 81, 'name' => 'Козловка'],
            ['region_id' => 40, 'name' => 'Козьмодемьянск'],
            ['region_id' => 44, 'name' => 'Кола'],
            ['region_id' => 32, 'name' => 'Кологрив'],
            ['region_id' => 70, 'name' => 'Колпашево'],
            ['region_id' => 12, 'name' => 'Кольчугино'],
            ['region_id' => 19, 'name' => 'Комсомольск'],
            ['region_id' => 69, 'name' => 'Конаково'],
            ['region_id' => 25, 'name' => 'Кондрово'],
            ['region_id' => 56, 'name' => 'Константиновск'],
            ['region_id' => 57, 'name' => 'Кораблино'],
            ['region_id' => 33, 'name' => 'Кореновск'],
            ['region_id' => 79, 'name' => 'Коркино'],
            ['region_id' => 9,  'name' => 'Короча'],
            ['region_id' => 62, 'name' => 'Корсаков'],
            ['region_id' => 6,  'name' => 'Коряжма'],
            ['region_id' => 12, 'name' => 'Костерёво'],
            ['region_id' => 28, 'name' => 'Костомукша'],
            ['region_id' => 13, 'name' => 'Котельниково'],
            ['region_id' => 30, 'name' => 'Котельнич'],
            ['region_id' => 13, 'name' => 'Котово'],
            ['region_id' => 67, 'name' => 'Котовск'],
            ['region_id' => 19, 'name' => 'Кохма'],
            ['region_id' => 14, 'name' => 'Красавино'],
            ['region_id' => 60, 'name' => 'Красноармейск (Саратовская область)'],
            ['region_id' => 53, 'name' => 'Красновишерск'],
            ['region_id' => 43, 'name' => 'Краснозаводск'],
            ['region_id' => 13, 'name' => 'Краснослободск (Волгоградская область)\r\n'],
            ['region_id' => 41, 'name' => 'Краснослободск (Мордовия)'],
            ['region_id' => 63, 'name' => 'Красноуральск'],
            ['region_id' => 63, 'name' => 'Красноуфимск'],
            ['region_id' => 60, 'name' => 'Красный Кут'],
            ['region_id' => 56, 'name' => 'Красный Сулин'],
            ['region_id' => 69, 'name' => 'Красный Холм'],
            ['region_id' => 25, 'name' => 'Кремёнки'],
            ['region_id' => 33, 'name' => 'Крымск'],
            ['region_id' => 50, 'name' => 'Кувандык'],
            ['region_id' => 69, 'name' => 'Кувшиново'],
            ['region_id' => 53, 'name' => 'Кудымкар'],
            ['region_id' => 46, 'name' => 'Кулебаки'],
            ['region_id' => 8,  'name' => 'Кумертау'],
            ['region_id' => 48, 'name' => 'Купино'],
            ['region_id' => 33, 'name' => 'Курганинск'],
            ['region_id' => 62, 'name' => 'Курильск'],
            ['region_id' => 12, 'name' => 'Курлово'],
            ['region_id' => 43, 'name' => 'Куровское'],
            ['region_id' => 35, 'name' => 'Куртамыш'],
            ['region_id' => 79, 'name' => 'Куса'],
            ['region_id' => 63, 'name' => 'Кушва'],
            ['region_id' => 79, 'name' => 'Кыштым'],
            ['region_id' => 11, 'name' => 'Кяхта'],
            ['region_id' => 33, 'name' => 'Лабинск'],
            ['region_id' => 83, 'name' => 'Лабытнанги'],
            ['region_id' => 24, 'name' => 'Лагань'],
            ['region_id' => 23, 'name' => 'Ладушкин'],
            ['region_id' => 68, 'name' => 'Лаишево'],
            ['region_id' => 12, 'name' => 'Лакинск'],
            ['region_id' => 78, 'name' => 'Лангепас'],
            ['region_id' => 28, 'name' => 'Лахденпохья'],
            ['region_id' => 38, 'name' => 'Лебедянь'],
            ['region_id' => 68, 'name' => 'Лениногорск'],
            ['region_id' => 13, 'name' => 'Ленинск'],
            ['region_id' => 61, 'name' => 'Ленск'],
            ['region_id' => 66, 'name' => 'Лермонтов'],
            ['region_id' => 63, 'name' => 'Лесной'],
            ['region_id' => 54, 'name' => 'Лесозаводск'],
            ['region_id' => 34, 'name' => 'Лесосибирск'],
            ['region_id' => 71, 'name' => 'Липки'],
            ['region_id' => 69, 'name' => 'Лихославль'],
            ['region_id' => 30, 'name' => 'Луза'],
            ['region_id' => 46, 'name' => 'Лукоянов'],
            ['region_id' => 46, 'name' => 'Лысково'],
            ['region_id' => 36, 'name' => 'Льгов'],
            ['region_id' => 37, 'name' => 'Любань'],
            ['region_id' => 84, 'name' => 'Любим'],
            ['region_id' => 25, 'name' => 'Людиново'],
            ['region_id' => 78, 'name' => 'Лянтор'],
            ['region_id' => 20, 'name' => 'Магас'],
            ['region_id' => 22, 'name' => 'Майский'],
            ['region_id' => 62, 'name' => 'Макаров'],
            ['region_id' => 32, 'name' => 'Макарьев'],
            ['region_id' => 35, 'name' => 'Макушино'],
            ['region_id' => 47, 'name' => 'Малая Вишера'],
            ['region_id' => 20, 'name' => 'Малгобек'],
            ['region_id' => 30, 'name' => 'Малмыж'],
            ['region_id' => 51, 'name' => 'Малоархангельск'],
            ['region_id' => 25, 'name' => 'Малоярославец'],
            ['region_id' => 68, 'name' => 'Мамадыш'],
            ['region_id' => 23, 'name' => 'Мамоново'],
            ['region_id' => 32, 'name' => 'Мантурово'],
            ['region_id' => 29, 'name' => 'Мариинск'],
            ['region_id' => 81, 'name' => 'Мариинский Посад'],
            ['region_id' => 60, 'name' => 'Маркс'],
            ['region_id' => 10, 'name' => 'Мглин'],
            ['region_id' => 78, 'name' => 'Мегион'],
            ['region_id' => 28, 'name' => 'Медвежьегорск'],
            ['region_id' => 50, 'name' => 'Медногорск'],
            ['region_id' => 25, 'name' => 'Медынь'],
            ['region_id' => 8,  'name' => 'Межгорье'],
            ['region_id' => 6,  'name' => 'Мезень'],
            ['region_id' => 12, 'name' => 'Меленки'],
            ['region_id' => 8,  'name' => 'Мелеуз'],
            ['region_id' => 68, 'name' => 'Менделеевск'],
            ['region_id' => 68, 'name' => 'Мензелинск'],
            ['region_id' => 25, 'name' => 'Мещовск'],
            ['region_id' => 31, 'name' => 'Микунь'],
            ['region_id' => 56, 'name' => 'Миллерово'],
            ['region_id' => 34, 'name' => 'Минусинск'],
            ['region_id' => 79, 'name' => 'Миньяр'],
            ['region_id' => 57, 'name' => 'Михайлов'],
            ['region_id' => 13, 'name' => 'Михайловка'],
            ['region_id' => 63, 'name' => 'Михайловск (Свердловская область)'],
            ['region_id' => 66, 'name' => 'Михайловск (Ставропольский край)'],
            ['region_id' => 18, 'name' => 'Могоча'],
            ['region_id' => 74, 'name' => 'Можга'],
            ['region_id' => 44, 'name' => 'Мончегорск'],
            ['region_id' => 56, 'name' => 'Морозовск'],
            ['region_id' => 67, 'name' => 'Моршанск'],
            ['region_id' => 25, 'name' => 'Мосальск'],
            ['region_id' => 83, 'name' => 'Муравленко'],
            ['region_id' => 30, 'name' => 'Мураши'],
            ['region_id' => 29, 'name' => 'Мыски'],
            ['region_id' => 84, 'name' => 'Мышкин'],
            ['region_id' => 46, 'name' => 'Навашино'],
            ['region_id' => 19, 'name' => 'Наволоки'],
            ['region_id' => 83, 'name' => 'Надым'],
            ['region_id' => 34, 'name' => 'Назарово'],
            ['region_id' => 49, 'name' => 'Называевск'],
            ['region_id' => 7,  'name' => 'Нариманов'],
            ['region_id' => 22, 'name' => 'Нарткала'],
            ['region_id' => 55, 'name' => 'Невель'],
            ['region_id' => 62, 'name' => 'Невельск'],
            ['region_id' => 66, 'name' => 'Невинномысск'],
            ['region_id' => 63, 'name' => 'Невьянск'],
            ['region_id' => 69, 'name' => 'Нелидово'],
            ['region_id' => 23, 'name' => 'Неман'],
            ['region_id' => 32, 'name' => 'Нерехта'],
            ['region_id' => 18, 'name' => 'Нерчинск'],
            ['region_id' => 23, 'name' => 'Нестеров'],
            ['region_id' => 58, 'name' => 'Нефтегорск'],
            ['region_id' => 66, 'name' => 'Нефтекумск'],
            ['region_id' => 32, 'name' => 'Нея'],
            ['region_id' => 21, 'name' => 'Нижнеудинск'],
            ['region_id' => 63, 'name' => 'Нижние Серги'],
            ['region_id' => 52, 'name' => 'Нижний Ломов'],
            ['region_id' => 63, 'name' => 'Нижняя Салда'],
            ['region_id' => 63, 'name' => 'Нижняя Тура'],
            ['region_id' => 13, 'name' => 'Николаевск'],
            ['region_id' => 76, 'name' => 'Николаевск-на-Амуре'],
            ['region_id' => 14, 'name' => 'Никольск (Вологодская область)'],
            ['region_id' => 52, 'name' => 'Никольск (Пензенская область)'],
            ['region_id' => 37, 'name' => 'Новая Ладога'],
            ['region_id' => 63, 'name' => 'Новая Ляля'],
            ['region_id' => 66, 'name' => 'Новоалександровск'],
            ['region_id' => 13, 'name' => 'Новоаннинский'],
            ['region_id' => 15, 'name' => 'Нововоронеж'],
            ['region_id' => 6,  'name' => 'Новодвинск'],
            ['region_id' => 10, 'name' => 'Новозыбков'],
            ['region_id' => 33, 'name' => 'Новокубанск'],
            ['region_id' => 57, 'name' => 'Новомичуринск'],
            ['region_id' => 66, 'name' => 'Новопавловск'],
            ['region_id' => 55, 'name' => 'Новоржев'],
            ['region_id' => 51, 'name' => 'Новосиль'],
            ['region_id' => 55, 'name' => 'Новосокольники'],
            ['region_id' => 60, 'name' => 'Новоузенск'],
            ['region_id' => 75, 'name' => 'Новоульяновск'],
            ['region_id' => 15, 'name' => 'Новохопёрск'],
            ['region_id' => 30, 'name' => 'Нолинск'],
            ['region_id' => 68, 'name' => 'Нурлат'],
            ['region_id' => 53, 'name' => 'Нытва'],
            ['region_id' => 61, 'name' => 'Нюрба'],
            ['region_id' => 78, 'name' => 'Нягань'],
            ['region_id' => 79, 'name' => 'Нязепетровск'],
            ['region_id' => 6,  'name' => 'Няндома'],
            ['region_id' => 17, 'name' => 'Облучье'],
            ['region_id' => 36, 'name' => 'Обоянь'],
            ['region_id' => 48, 'name' => 'Обь'],
            ['region_id' => 43, 'name' => 'Ожерелье'],
            ['region_id' => 58, 'name' => 'Октябрьск'],
            ['region_id' => 47, 'name' => 'Окуловка'],
            ['region_id' => 61, 'name' => 'Олёкминск'],
            ['region_id' => 44, 'name' => 'Оленегорск'],
            ['region_id' => 28, 'name' => 'Олонец'],
            ['region_id' => 30, 'name' => 'Омутнинск'],
            ['region_id' => 6,  'name' => 'Онега'],
            ['region_id' => 55, 'name' => 'Опочка'],
            ['region_id' => 30, 'name' => 'Орлов'],
            ['region_id' => 53, 'name' => 'Оса'],
            ['region_id' => 29, 'name' => 'Осинники'],
            ['region_id' => 69, 'name' => 'Осташков'],
            ['region_id' => 55, 'name' => 'Остров'],
            ['region_id' => 44, 'name' => 'Островной'],
            ['region_id' => 15, 'name' => 'Острогожск'],
            ['region_id' => 58, 'name' => 'Отрадный'],
            ['region_id' => 62, 'name' => 'Оха'],
            ['region_id' => 53, 'name' => 'Оханск'],
            ['region_id' => 53, 'name' => 'Очёр'],
            ['region_id' => 13, 'name' => 'Палласовка'],
            ['region_id' => 54, 'name' => 'Партизанск'],
            ['region_id' => 82, 'name' => 'Певек'],
            ['region_id' => 46, 'name' => 'Первомайск'],
            ['region_id' => 46, 'name' => 'Перевоз'],
            ['region_id' => 43, 'name' => 'Пересвет'],
            ['region_id' => 47, 'name' => 'Пестово'],
            ['region_id' => 13, 'name' => 'Петров Вал'],
            ['region_id' => 60, 'name' => 'Петровск'],
            ['region_id' => 18, 'name' => 'Петровск-Забайкальский'],
            ['region_id' => 35, 'name' => 'Петухово'],
            ['region_id' => 12, 'name' => 'Петушки'],
            ['region_id' => 55, 'name' => 'Печоры'],
            ['region_id' => 23, 'name' => 'Пионерский'],
            ['region_id' => 28, 'name' => 'Питкяранта'],
            ['region_id' => 19, 'name' => 'Плёс'],
            ['region_id' => 71, 'name' => 'Плавск'],
            ['region_id' => 79, 'name' => 'Пласт'],
            ['region_id' => 15, 'name' => 'Поворино'],
            ['region_id' => 78, 'name' => 'Покачи'],
            ['region_id' => 12, 'name' => 'Покров'],
            ['region_id' => 61, 'name' => 'Покровск'],
            ['region_id' => 23, 'name' => 'Полесск'],
            ['region_id' => 29, 'name' => 'Полысаево'],
            ['region_id' => 44, 'name' => 'Полярные Зори'],
            ['region_id' => 44, 'name' => 'Полярный'],
            ['region_id' => 62, 'name' => 'Поронайск'],
            ['region_id' => 55, 'name' => 'Порхов'],
            ['region_id' => 58, 'name' => 'Похвистнево'],
            ['region_id' => 10, 'name' => 'Почеп'],
            ['region_id' => 65, 'name' => 'Починок'],
            ['region_id' => 84, 'name' => 'Пошехонье'],
            ['region_id' => 23, 'name' => 'Правдинск'],
            ['region_id' => 19, 'name' => 'Приволжск'],
            ['region_id' => 23, 'name' => 'Приморск (Калининградская область)'],
            ['region_id' => 37, 'name' => 'Приморск (Ленинградская область)'],
            ['region_id' => 33, 'name' => 'Приморско-Ахтарск'],
            ['region_id' => 56, 'name' => 'Пролетарск'],
            ['region_id' => 60, 'name' => 'Пугачёв'],
            ['region_id' => 28, 'name' => 'Пудож'],
            ['region_id' => 55, 'name' => 'Пустошка'],
            ['region_id' => 19, 'name' => 'Пучеж'],
            ['region_id' => 55, 'name' => 'Пыталово'],
            ['region_id' => 78, 'name' => 'Пыть-Ях'],
            ['region_id' => 12, 'name' => 'Радужный (Владимирская область)'],
            ['region_id' => 78, 'name' => 'Радужный (Ханты-Мансийский АО - Югра)'],
            ['region_id' => 5,  'name' => 'Райчихинск'],
            ['region_id' => 67, 'name' => 'Рассказово'],
            ['region_id' => 63, 'name' => 'Реж'],
            ['region_id' => 19, 'name' => 'Родники'],
            ['region_id' => 65, 'name' => 'Рославль'],
            ['region_id' => 84, 'name' => 'Ростов'],
            ['region_id' => 60, 'name' => 'Ртищево'],
            ['region_id' => 65, 'name' => 'Рудня'],
            ['region_id' => 43, 'name' => 'Руза'],
            ['region_id' => 57, 'name' => 'Рыбное'],
            ['region_id' => 36, 'name' => 'Рыльск'],
            ['region_id' => 57, 'name' => 'Ряжск'],
            ['region_id' => 29, 'name' => 'Салаир'],
            ['region_id' => 83, 'name' => 'Салехард'],
            ['region_id' => 57, 'name' => 'Сасово'],
            ['region_id' => 65, 'name' => 'Сафоново'],
            ['region_id' => 77, 'name' => 'Саяногорск'],
            ['region_id' => 21, 'name' => 'Саянск'],
            ['region_id' => 23, 'name' => 'Светлогорск'],
            ['region_id' => 66, 'name' => 'Светлоград'],
            ['region_id' => 23, 'name' => 'Светлый'],
            ['region_id' => 21, 'name' => 'Свирск'],
            ['region_id' => 55, 'name' => 'Себеж'],
            ['region_id' => 62, 'name' => 'Северо-Курильск'],
            ['region_id' => 63, 'name' => 'Североуральск'],
            ['region_id' => 10, 'name' => 'Севск'],
            ['region_id' => 28, 'name' => 'Сегежа'],
            ['region_id' => 10, 'name' => 'Сельцо'],
            ['region_id' => 46, 'name' => 'Семёнов'],
            ['region_id' => 56, 'name' => 'Семикаракорск'],
            ['region_id' => 15, 'name' => 'Семилуки'],
            ['region_id' => 75, 'name' => 'Сенгилей'],
            ['region_id' => 13, 'name' => 'Серафимович'],
            ['region_id' => 46, 'name' => 'Сергач'],
            ['region_id' => 52, 'name' => 'Сердобск'],
            ['region_id' => 8,  'name' => 'Сибай'],
            ['region_id' => 79, 'name' => 'Сим'],
            ['region_id' => 5,  'name' => 'Сковородино'],
            ['region_id' => 57, 'name' => 'Скопин'],
            ['region_id' => 4,  'name' => 'Славгород'],
            ['region_id' => 23, 'name' => 'Славск'],
            ['region_id' => 33, 'name' => 'Славянск-на-Кубани'],
            ['region_id' => 30, 'name' => 'Слободской'],
            ['region_id' => 21, 'name' => 'Слюдянка'],
            ['region_id' => 44, 'name' => 'Снежногорск'],
            ['region_id' => 12, 'name' => 'Собинка'],
            ['region_id' => 30, 'name' => 'Советск (Кировская область)'],
            ['region_id' => 71, 'name' => 'Советск (Тульская область)'],
            ['region_id' => 76, 'name' => 'Советская Гавань'],
            ['region_id' => 78, 'name' => 'Советский'],
            ['region_id' => 32, 'name' => 'Солигалич'],
            ['region_id' => 50, 'name' => 'Соль-Илецк'],
            ['region_id' => 6,  'name' => 'Сольвычегодск'],
            ['region_id' => 47, 'name' => 'Сольцы'],
            ['region_id' => 50, 'name' => 'Сорочинск'],
            ['region_id' => 77, 'name' => 'Сорск'],
            ['region_id' => 28, 'name' => 'Сортавала'],
            ['region_id' => 25, 'name' => 'Сосенский'],
            ['region_id' => 30, 'name' => 'Сосновка'],
            ['region_id' => 34, 'name' => 'Сосновоборск'],
            ['region_id' => 31, 'name' => 'Сосногорск'],
            ['region_id' => 25, 'name' => 'Спас-Деменск'],
            ['region_id' => 57, 'name' => 'Спас-Клепики'],
            ['region_id' => 52, 'name' => 'Спасск'],
            ['region_id' => 54, 'name' => 'Спасск-Дальний'],
            ['region_id' => 57, 'name' => 'Спасск-Рязанский'],
            ['region_id' => 61, 'name' => 'Среднеколымск'],
            ['region_id' => 63, 'name' => 'Среднеуральск'],
            ['region_id' => 18, 'name' => 'Сретенск'],
            ['region_id' => 69, 'name' => 'Старица'],
            ['region_id' => 10, 'name' => 'Стародуб'],
            ['region_id' => 70, 'name' => 'Стрежевой'],
            ['region_id' => 9,  'name' => 'Строитель'],
            ['region_id' => 12, 'name' => 'Струнино'],
            ['region_id' => 71, 'name' => 'Суворов'],
            ['region_id' => 36, 'name' => 'Суджа'],
            ['region_id' => 12, 'name' => 'Судогда'],
            ['region_id' => 12, 'name' => 'Суздаль'],
            ['region_id' => 28, 'name' => 'Суоярви'],
            ['region_id' => 10, 'name' => 'Сураж'],
            ['region_id' => 13, 'name' => 'Суровикино'],
            ['region_id' => 52, 'name' => 'Сурск'],
            ['region_id' => 39, 'name' => 'Сусуман'],
            ['region_id' => 25, 'name' => 'Сухиничи'],
            ['region_id' => 63, 'name' => 'Сухой Лог'],
            ['region_id' => 63, 'name' => 'Сысерть'],
            ['region_id' => 65, 'name' => 'Сычёвка'],
            ['region_id' => 63, 'name' => 'Тавда'],
            ['region_id' => 29, 'name' => 'Тайга'],
            ['region_id' => 21, 'name' => 'Тайшет'],
            ['region_id' => 43, 'name' => 'Талдом'],
            ['region_id' => 63, 'name' => 'Талица'],
            ['region_id' => 49, 'name' => 'Тара'],
            ['region_id' => 83, 'name' => 'Тарко-Сале'],
            ['region_id' => 25, 'name' => 'Таруса'],
            ['region_id' => 48, 'name' => 'Татарск'],
            ['region_id' => 29, 'name' => 'Таштагол'],
            ['region_id' => 27, 'name' => 'Теберда'],
            ['region_id' => 19, 'name' => 'Тейково'],
            ['region_id' => 41, 'name' => 'Темников'],
            ['region_id' => 33, 'name' => 'Темрюк'],
            ['region_id' => 22, 'name' => 'Терек'],
            ['region_id' => 68, 'name' => 'Тетюши'],
            ['region_id' => 33, 'name' => 'Тимашевск'],
            ['region_id' => 48, 'name' => 'Тогучин'],
            ['region_id' => 62, 'name' => 'Томари'],
            ['region_id' => 61, 'name' => 'Томмот'],
            ['region_id' => 29, 'name' => 'Топки'],
            ['region_id' => 69, 'name' => 'Торжок'],
            ['region_id' => 69, 'name' => 'Торопец'],
            ['region_id' => 14, 'name' => 'Тотьма'],
            ['region_id' => 79, 'name' => 'Трёхгорный'],
            ['region_id' => 10, 'name' => 'Трубчевск'],
            ['region_id' => 8,  'name' => 'Туймазы'],
            ['region_id' => 21, 'name' => 'Тулун'],
            ['region_id' => 72, 'name' => 'Туран'],
            ['region_id' => 63, 'name' => 'Туринск'],
            ['region_id' => 84, 'name' => 'Тутаев'],
            ['region_id' => 5,  'name' => 'Тында'],
            ['region_id' => 22, 'name' => 'Тырныауз'],
            ['region_id' => 49, 'name' => 'Тюкалинск'],
            ['region_id' => 67, 'name' => 'Уварово'],
            ['region_id' => 62, 'name' => 'Углегорск'],
            ['region_id' => 84, 'name' => 'Углич'],
            ['region_id' => 61, 'name' => 'Удачный'],
            ['region_id' => 69, 'name' => 'Удомля'],
            ['region_id' => 34, 'name' => 'Ужур'],
            ['region_id' => 10, 'name' => 'Унеча'],
            ['region_id' => 78, 'name' => 'Урай'],
            ['region_id' => 46, 'name' => 'Урень'],
            ['region_id' => 30, 'name' => 'Уржум'],
            ['region_id' => 13, 'name' => 'Урюпинск'],
            ['region_id' => 31, 'name' => 'Усинск'],
            ['region_id' => 38, 'name' => 'Усмань'],
            ['region_id' => 53, 'name' => 'Усолье'],
            ['region_id' => 21, 'name' => 'Усолье-Сибирское'],
            ['region_id' => 27, 'name' => 'Усть-Джегута'],
            ['region_id' => 79, 'name' => 'Усть-Катав'],
            ['region_id' => 21, 'name' => 'Усть-Кут'],
            ['region_id' => 33, 'name' => 'Усть-Лабинск'],
            ['region_id' => 14, 'name' => 'Устюжна'],
            ['region_id' => 8,  'name' => 'Учалы'],
            ['region_id' => 34, 'name' => 'Уяр'],
            ['region_id' => 36, 'name' => 'Фатеж'],
            ['region_id' => 10, 'name' => 'Фокино (Брянская область)'],
            ['region_id' => 54, 'name' => 'Фокино (Приморский край)\n'],
            ['region_id' => 13, 'name' => 'Фролово'],
            ['region_id' => 19, 'name' => 'Фурманов'],
            ['region_id' => 33, 'name' => 'Хадыженск'],
            ['region_id' => 7,  'name' => 'Харабали'],
            ['region_id' => 14, 'name' => 'Харовск'],
            ['region_id' => 60, 'name' => 'Хвалынск'],
            ['region_id' => 18, 'name' => 'Хилок'],
            ['region_id' => 47, 'name' => 'Холм'],
            ['region_id' => 62, 'name' => 'Холмск'],
            ['region_id' => 43, 'name' => 'Хотьково'],
            ['region_id' => 81, 'name' => 'Цивильск'],
            ['region_id' => 56, 'name' => 'Цимлянск'],
            ['region_id' => 53, 'name' => 'Чёрмоз'],
            ['region_id' => 72, 'name' => 'Чадан'],
            ['region_id' => 38, 'name' => 'Чаплыгин'],
            ['region_id' => 79, 'name' => 'Чебаркуль'],
            ['region_id' => 22, 'name' => 'Чегем'],
            ['region_id' => 71, 'name' => 'Чекалин'],
            ['region_id' => 53, 'name' => 'Чердынь'],
            ['region_id' => 21, 'name' => 'Черемхово'],
            ['region_id' => 48, 'name' => 'Черепаново'],
            ['region_id' => 53, 'name' => 'Чернушка'],
            ['region_id' => 23, 'name' => 'Черняховск'],
            ['region_id' => 68, 'name' => 'Чистополь'],
            ['region_id' => 46, 'name' => 'Чкаловск'],
            ['region_id' => 47, 'name' => 'Чудово'],
            ['region_id' => 48, 'name' => 'Чулым'],
            ['region_id' => 53, 'name' => 'Чусовой'],
            ['region_id' => 32, 'name' => 'Чухлома'],
            ['region_id' => 72, 'name' => 'Шагонар'],
            ['region_id' => 80, 'name' => 'Шали'],
            ['region_id' => 34, 'name' => 'Шарыпово'],
            ['region_id' => 32, 'name' => 'Шарья'],
            ['region_id' => 62, 'name' => 'Шахтёрск'],
            ['region_id' => 46, 'name' => 'Шахунья'],
            ['region_id' => 57, 'name' => 'Шацк'],
            ['region_id' => 21, 'name' => 'Шелехов'],
            ['region_id' => 6,  'name' => 'Шенкурск'],
            ['region_id' => 18, 'name' => 'Шилка'],
            ['region_id' => 5,  'name' => 'Шимановск'],
            ['region_id' => 60, 'name' => 'Шиханы'],
            ['region_id' => 81, 'name' => 'Шумерля'],
            ['region_id' => 35, 'name' => 'Шумиха'],
            ['region_id' => 71, 'name' => 'Щёкино'],
            ['region_id' => 36, 'name' => 'Щигры'],
            ['region_id' => 35, 'name' => 'Щучье'],
            ['region_id' => 15, 'name' => 'Эртиль'],
            ['region_id' => 78, 'name' => 'Югорск'],
            ['region_id' => 19, 'name' => 'Южа'],
            ['region_id' => 16, 'name' => 'Южно-Сухокумск'],
            ['region_id' => 79, 'name' => 'Южноуральск'],
            ['region_id' => 12, 'name' => 'Юрьев-Польский'],
            ['region_id' => 19, 'name' => 'Юрьевец'],
            ['region_id' => 79, 'name' => 'Юрюзань'],
            ['region_id' => 25, 'name' => 'Юхнов'],
            ['region_id' => 81, 'name' => 'Ядрин'],
            ['region_id' => 73, 'name' => 'Ялуторовск'],
            ['region_id' => 8,  'name' => 'Янаул'],
            ['region_id' => 30, 'name' => 'Яранск'],
            ['region_id' => 4,  'name' => 'Яровое'],
            ['region_id' => 65, 'name' => 'Ярцево'],
            ['region_id' => 71, 'name' => 'Ясногорск'],
            ['region_id' => 50, 'name' => 'Ясный'],
            ['region_id' => 43, 'name' => 'Яхрома'],
            ['region_id' => 85, 'name' => 'Алупка'],
            ['region_id' => 85, 'name' => 'Алушта'],
            ['region_id' => 85, 'name' => 'Армянск'],
            ['region_id' => 85, 'name' => 'Бахчисарай'],
            ['region_id' => 85, 'name' => 'Белогорск (Крым)'],
            ['region_id' => 85, 'name' => 'Джанкой'],
            ['region_id' => 85, 'name' => 'Евпатория'],
            ['region_id' => 86, 'name' => 'Инкерман'],
            ['region_id' => 68, 'name' => 'Иннополис'],
            ['region_id' => 85, 'name' => 'Керчь'],
            ['region_id' => 23, 'name' => 'Краснознаменск (Калининградская область)'],
            ['region_id' => 85, 'name' => 'Красноперекопск'],
            ['region_id' => 6,  'name' => 'Мирный (Архангельская область)'],
            ['region_id' => 23, 'name' => 'Озерск (Калининградская область)'],
            ['region_id' => 85, 'name' => 'Саки'],
            ['region_id' => 86, 'name' => 'Севастополь'],
            ['region_id' => 85, 'name' => 'Симферополь'],
            ['region_id' => 85, 'name' => 'Старый Крым'],
            ['region_id' => 85, 'name' => 'Судак'],
            ['region_id' => 5,  'name' => 'Циолковский'],
            ['region_id' => 85, 'name' => 'Феодосия'],
            ['region_id' => 85, 'name' => 'Щелкино'],
            ['region_id' => 85, 'name' => 'Ялта']
        ]);

        foreach ($citiesInRussia as $cityInRussia) {
            foreach ($cityInRussia as $city) {
                if ($city['name'] == 'не выбрано') {
                    DB::table('cities')->insert(['region_id' => $city['region_id'], 'name' => $city['name'], 'InEnglish' => 'no selected']);
                } elseif ($city['name'] == 'Москва') {
                    DB::table('cities')->insert(['region_id' => $city['region_id'], 'name' => $city['name'], 'InEnglish' => 'Moscow']);
                } else {
                    DB::table('cities')->insert(['region_id' => $city['region_id'], 'name' => $city['name'], 'InEnglish' => translit($city['name'])]);
                }
            }
        }

        /* Add categories for group*/
        DB::table('categories')->insert([
            'name' => 'Общины',
            'sort_id' => 0,
            'created_at' => '2023-06-28 14:18:19',
            'updated_at' => '2023-06-28 14:18:19',
            'type' => 'group'
        ]);
        DB::table('categories')->insert([
            'name' => 'Сообщества',
            'sort_id' => 1,
            'created_at' => '2023-06-28 14:18:19',
            'updated_at' => '2023-06-28 14:18:19',
            'type' => 'group'
        ]);
        DB::table('categories')->insert([
            'name' => 'Школы',
            'sort_id' => 2,
            'created_at' => '2023-06-28 14:18:19',
            'updated_at' => '2023-06-28 14:18:19',
            'type' => 'group'
        ]);
        DB::table('categories')->insert([
            'name' => 'Кружки и секции',
            'sort_id' => 3,
            'created_at' => '2023-06-28 14:18:19',
            'updated_at' => '2023-06-28 14:18:19',
            'type' => 'group'
        ]);
        DB::table('categories')->insert([
            'name' => 'Религия',
            'sort_id' => 4,
            'created_at' => '2023-06-28 14:18:19',
            'updated_at' => '2023-06-28 14:18:19',
            'type' => 'group'
        ]);
        DB::table('categories')->insert([
            'name' => 'Интересные места',
            'sort_id' => 5,
            'created_at' => '2023-06-28 14:18:19',
            'updated_at' => '2023-06-28 14:18:19',
            'type' => 'group'
        ]);
        DB::table('categories')->insert([
            'name' => 'Прочее',
            'sort_id' => 6,
            'created_at' => '2023-06-28 14:18:19',
            'updated_at' => '2023-06-28 14:18:19',
            'type' => 'group'
        ]);

        /* Add categories for offer*/
        DB::table('categories')->insert([
            'name' => 'Траснпорт',
            'sort_id' => 0,
            'created_at' => '2023-06-28 14:18:19',
            'updated_at' => '2023-06-28 14:18:19',
            'type' => 'offer'
        ]);
        DB::table('categories')->insert([
            'name' => 'Дом и строительство',
            'sort_id' => 1,
            'created_at' => '2023-06-28 14:18:19',
            'updated_at' => '2023-06-28 14:18:19',
            'type' => 'offer'
        ]);

        /* Add categories for event*/
        DB::table('categories')->insert([
            'name' => 'Вечеринка',
            'sort_id' => 0,
            'created_at' => '2023-06-28 14:18:19',
            'updated_at' => '2023-06-28 14:18:19',
            'type' => 'event'
        ]);
        DB::table('categories')->insert([
            'name' => 'Разное',
            'sort_id' => 1,
            'created_at' => '2023-06-28 14:18:19',
            'updated_at' => '2023-06-28 14:18:19',
            'type' => 'event'
        ]);

        /* Add groups */
        $i = 1;
        foreach ($regionsInRussia as $region) {
            foreach ($regionInRussia as $region) {
                DB::table('groups')->insert([
                    'created_at' => '2023-06-28 14:18:19',
                    'updated_at' => '2023-06-28 14:18:19',
                    'name' => 'Армянская община ' . $region['name'],
                    'image' => 'groups/groups.png',
                    'city_id' => 1,
                    'region_id' => $i++,
                    'category_id' => 1
                ]);
            }
        }
    }
}
